### ISSUE TITLE
Implement XDS-style scaling model as least mathematically complex scaling

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#405] opened 2017-06-30 14:20 UTC
i.e. following from #404 implement Kabsch model for scaling on arrays of correction factors with LBFGS minimiser, should be simple and converge quickly for high multiplicity data. 

DECAY MODULATION ABSORPTION in sequence not concurrent or in macrocycles, though these should be explored with the design.

**Comment by biochem-fan** [comment] 2017-10-11 20:26
Hi, I am following scaling codes at DIALS-scratch with great interests.

I have studied XSCALE algorithm some times ago. I calculated actual scale factors by dividing scaled-but-unmerged outputs by non-scaled, un-merged inputs. For example, we can run `NBATCH=1 CORRECTIONS=ABSORP` to see what ABSORP actually does.

What I found but is not obvious from the paper is that actual scale factors are NOT exactly those defined on discrete grids (, which are written to `ABSORP.cbf`), but somehow smoothened. The weighting function seemed Gaussian, but I am not very sure.

I attached one example. These are the actual scale factors along XOBS within a small bin of YOBS. The red lines are grids defined in `XSCALE.LP`. Smoothing is obvious.

I did this analysis in R, but a similar tool in Python is trivial to implement, and might be useful for study.

![image](https://user-images.githubusercontent.com/1611483/31464958-796e8378-aeca-11e7-8379-7a3432102c67.png)

**Comment by graeme-winter** [comment] 2017-10-11 20:28
I have always suspected this to be the case but very much welcome this input. We should - as you suggest - reproduce these results from the data to verify the form

**Comment by biochem-fan** [comment] 2017-10-11 20:33
Another example in 2D from @yam_cpp on Twitter.
https://twitter.com/yam_cpp/status/715068603620417536

**Comment by dagewa** [comment] 2017-10-12 05:56
I'm pretty sure Phil said he got the Gaussian smoother idea from Kabsch. We should check with him.

**Comment by graeme-winter** [comment] 2017-10-12 05:58
No mistake @dagewa however I think the point is that this Gaussian smoother is not explicitly described in the paper despite being used... the 1D Gaussian Phil uses for k, B and you implemented for scan varying refinement probably shares a common heritage with the 2D smoothers used here...

**Comment by dagewa** [comment] 2017-10-13 23:59
Smoothing is described obliquely in [W. Kabsch J. Appl. Cryst. (1988). 21, 67-72](http://journals.iucr.org/j/issues/1988/06/00/wi0031/wi0031.pdf) as a "modification to the method of Fox & Holmes" using weights w_{hlα} "which depend upon the distance from each reflection to the positions α of the scale factors". The positions α are the same as the reference profiles (9 on the detector plane, each block of a few degrees). It isn't mentioned in the paper that the weighting function is Gaussian, but my understanding that it is so.

**Comment by dagewa** [comment] 2017-10-18 13:29
I found that the use of a Gaussian smoother by XDS is confirmed in the [2006 edition of Int. Tab.F](http://it.iucr.org/Fa/ch11o3v0001/sec11o3o4/), while the description in the newer edition is shorter and omits that point.

> The main difference from the method of Fox & Holmes (1966[link]) is the introduction of the weights [w_{hl\alpha}]. These weights depend upon the distance between each reflection hl and the positions α. They are monotonically decreasing functions of this distance, implemented as Gaussians in XDS and XSCALE. This results in a smoothing of the scaling factors since each reflection contributes to the observational equations in proportion to the weights [w_{hl\alpha}].

The implication is that the 2D smoothing is actually achieved by using the sum of Gaussian weighted sub-parameter values, where the domain of the Gaussian functions is the 1D distance of each reflection from the relevant α positions. In AIMLESS the smooth-φ scales are calculated using the nearest 3 sub-parameters, but you could always use more. I suppose for 2D you would want to use the nearest 4 positions or possibly 6 for a rectangular grid. However, XDS uses a circular grid and maybe the nearest 3 positions are sufficient.

**Comment by jbeilstenedmands** [comment] 2017-10-18 13:45
Hi David,

Thanks for clarifying. I've been implementing smooth scale factors over the
past few days, for 1D smoothing in aimless-like parameterisation and 2D
smoothing in XDS-like parameterisation. I have found that for aimless
scaling, the number of nearest parameters to use depends a bit on the
parameters chosen such as the 'variance' of the gaussian smoothers and
depending on how much bumpiness you can tolerate for your smooth scale
factors (I prefer smoother smooth scales!). Okay, sounds like the approach
I have taken for XDS-like scaling is similar to that described, I've
implemented these on a square grid so far and I'm about to investigate
other grids for the absorption correction.

James

**Comment by biochem-fan** [comment] 2017-10-18 13:52
Hi David,

Great discovery!

I thought the description in Int. Tab. F is the same as Acta D. 2010.
Another difference is that the current implementation no longer uses a normal matrix,
which will be too big for many parameters. The cyclic update of parameters and the reference
described in Acta D seems better suited for large scaling.

**Comment by dagewa** [comment] 2017-10-18 13:53
Hi James, very good. By the way, the code in [gaussian_smoother.h](https://github.com/dials/dials/blob/master/algorithms/refinement/gaussian_smoother.h) is basically a faithful copy of what Aimless does. It is generic (i.e. not limited to geometry refinement) and I think could be re-used in scaling. That might be what you've done already, but I just wanted to make sure you were aware of it.

For scan-varying geometry refinement, using the nearest 3 parameters gives smooth enough parameters. A tiny discontinuity can always be seen at the positions where the smoother moves over from one set of 3 parameters to the next (i.e. A+B+C to B+C+D), but this is too small to worry about. The discontinuity can be reduced by including more parameters, but never reduced to zero of course.

**Comment by dagewa** [comment] 2017-10-18 14:01
PS actually, the Python interface to a smoothed parameter set in [scan_varying_model_parameters.py](https://github.com/dials/dials/blob/master/algorithms/refinement/parameterisation/scan_varying_model_parameters.py) is probably a more useful starting point. There is a basic test of the smoother in [tst_scan_varying_model_parameters.py](https://github.com/dials/dials/blob/master/test/algorithms/refinement/tst_scan_varying_model_parameters.py). You may well find improvements to these implementations, which we should merge in.

**Comment by jbeilstenedmands** [comment] 2017-10-18 14:03
Hi David, 
Yes I saw this the other day after I'd had a go in python, I think it's doing the same thing and I'll probably try to incorporate this into my code in future. Yes I noticed the bumpiness when moving between sets of parameters, I found it can basically be reduced to negligible if you include enough parameters such that the gaussian weight has dropped off to zero - I think if you include Phil's suggestion of a variance of 1 and 3 parameters then you only just get past one gaussian half-width in the distance between parameters which gave significant discontinuity. A lower variance gives greater difference between neighbouring parameters but less discontinuity. Also the ideal smoothing parameters seem to depend on the density of the scaling parameters - I guess there's probably a decent range of smoothing parameters and density of scaling parameters which gives very similar overall scaling results.

**Comment by dagewa** [comment] 2017-10-18 14:06
@biochem-fan agreed, true normal matrix methods are probably not going to get us very far. Aimless uses a BFGS algorithm derived from Phaser (see the `MinLib/` directory in Aimless source). There may be other methods that are suitable, and we should especially look for algorithms that are efficiently parallelisable.

**Comment by dagewa** [comment] 2017-10-18 14:09
@jbeilstenedmands I think I use the defaults from Aimless. At least according to the dials.refine paper:

> ...the number of nearest points over which to average is set to three, as no significant advantage was observed by increasing the number of points. In addition, the width of the Gaussian functions is linked to the interval width such that at the maximum of one Gaussian the adjacent Gaussians are at 13% of their maximum values.

I can well believe that the optimum requirements for scaling differ from geometry refinement though.

**Comment by dagewa** [comment] 2017-10-18 14:17
Oh, and the implementation in Aimless (and dials.refine) sets the sigma of the Gaussian according to `sigma_ = 0.65 + 0.05 * (naverage - 2);` naverage is usually 3, so the sigma is 0.7 (in normalised coordinates)

**Comment by biochem-fan** [comment] 2017-10-18 14:39
@dagewa did you try the method in Acta D, 2010? It is trivial to parallelise.

Section 3.7.5 of the nXDS paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4118830/) describes another variant of the method. I don't quite understand it though. It determines image scale factors g_l, but g_l and B factors also seems to be updated during post-refinement described in the next section. Is the quadratic method in 3.7.5 only used to determine initial values of g_l?

**Comment by dagewa** [comment] 2017-10-18 15:11
Hi Takanori, no we haven't tried that yet, but we are getting there. I have
not looked at the nXDS paper for a long time. Useful reminder, thanks.

-- David

**Comment by dagewa** [comment] 2018-04-26 15:40
@jbeilstenedmands I'm just browsing old issues and saw this one. It might be one you can close?

**Comment by jbeilstenedmands** [comment] 2018-04-26 15:53
Yes this can be closed now, array based models are implemented and minimised by LBFGS/full-matrix methods. However this reminds me that I should revisit the method from Acta D, 2010 and see if this is more suitable for large datasets.

**Closed by jbeilstenedmands** 2018-04-26 15:53 UTC
