### ISSUE TITLE
dials.report - please could we make plots more useful for multi-panel detectors

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#482] opened 2017-12-06 06:09 UTC
At the moment detectors like the P12M make some of the plots in the report a little unhelpful

If we know a priori the geometry, could pass in => can make more easily interpreted plots (say with 24 modules for the rmsd plots)

**Comment by dagewa** [comment] 2017-12-06 06:48
Duplicate of #304

**Comment by graeme-winter** [comment] 2017-12-06 16:13
Found that adding (195+17)*panel_no to y coordinates in mm made all of this do $sensible things

**Comment by rjgildea** [comment] 2017-12-07 09:20
Closed as duplicate issue

**Closed by rjgildea** 2017-12-07 09:20 UTC
