### ISSUE TITLE
mosaicity proportional to image width

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#342] opened 2017-05-12 15:50 UTC
For screening images collected on I04 today, the mosaicity estimate reported by xia2/dials appears to be proportional to the image width (approximately double the image width):

Th_3_2_: 0.15 deg oscillation
Th_3_4_: 0.05 deg oscillation
Th_3_5_: 0.10 deg oscillation
Th_3_6_: 0.20 deg oscillation
Th_3_7_: 0.25 deg oscillation

```
$ grep Mosaic /dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_[2-7]_/xia2strategy/xia2.strategy.txt
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_2_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.033 < 0.033 < 0.033
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_2_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.035 < 0.035 < 0.035
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_2_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.034 < 0.034 < 0.034
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_4_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.011 < 0.011 < 0.011
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_4_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.011 < 0.011 < 0.011
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_4_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.013 < 0.013 < 0.013
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_5_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.023 < 0.023 < 0.023
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_5_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.021 < 0.021 < 0.021
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_5_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.023 < 0.023 < 0.023
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_6_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.044 < 0.044 < 0.044
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_6_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.045 < 0.045 < 0.045
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_6_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.043 < 0.043 < 0.043
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_7_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.054 < 0.054 < 0.054
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_7_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.058 < 0.058 < 0.058
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_7_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.056 < 0.056 < 0.056
```

For rotation datasets there also appears to be some dependence on image width, although not as extreme as above:

Th_3_9_: 0.05 deg oscillation
Th_3_10_: 0.10 deg oscillation
Th_3_11_: 0.15 deg oscillation
Th_3_12_: 0.20 deg oscillation
Th_3_16_: 0.10 deg oscillation (should be same as Th_3_10_)

```
$ grep Mosaic Th_3_*_/xia2/dials-run/xia2.txt 
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_9_/xia2/dials-run/xia2.txt:Mosaic spread: 0.062 < 0.062 < 0.062
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_10_/xia2/dials-run/xia2.txt:Mosaic spread: 0.072 < 0.072 < 0.072
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_11_/xia2/dials-run/xia2.txt:Mosaic spread: 0.077 < 0.077 < 0.077
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_12_/xia2/dials-run/xia2.txt:Mosaic spread: 0.080 < 0.080 < 0.080
/dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_16_/xia2/dials-run/xia2.txt:Mosaic spread: 0.072 < 0.072 < 0.072
```

**Comment by jmp1985** [comment] 2017-05-15 09:32
This is related to #119. I've added a new algorithm sigma_m_algorithm=extended to try and address this. It is currently not the default but will be once I've made the algorithm a bit faster and tested more thoroughly.

**Comment by rjgildea** [comment] 2017-05-15 11:31
Thanks - I'll test xia2.strategy on the above datasets using sigma_m_algorithm=extended to see if it improves things.

**Comment by rjgildea** [comment] 2017-05-15 13:37
Setting sigma_m_algorithm=extended seems to make things much worse for single images (sigma m = 0.000010 degrees):

Defaults:
```
$ grep sigma_m /dls/i04/data/2017/cm16781-2/processed/gw/20170512/Thaumat/Th_3/Th_3_2_/xia2strategy/DEFAULT/NATIVE/SWEEP1/integrate/19_integrated_experiments.json 
      "sigma_m": 0.033282133314629134,
```

sigma_m_algorithm=extended:
```
$ grep sigma_m /dls/i04/data/2017/cm16781-2/processing/rjgildea/20170512/screening/Th_3_2/DEFAULT/NATIVE/SWEEP1/integrate/19_integrated_experiments.json 
      "sigma_m": 9.999999999999969e-06, 
```

**Comment by jmp1985** [comment] 2017-05-15 13:56
Hi Richard,

In the new algorithm, I'm making use of intensity information on each image which should make things work better for oscillations but may have problems for a single image. I'll have a look at the data and see if there is anything I can do to improve things.

James

________________________________

**Comment by jmp1985** [comment] 2017-05-15 16:13
OK, additional information. In the case of the single images, both ML methods are giving tiny values for the mosaicity. The default algorithm therefore defaults to computing a naive variance which at least gives a value. However, it scales with the oscillation width.

**Comment by jmp1985** [comment] 2017-05-15 16:17
I think that part of the problem is that for the single images, all the reflections used to compute the mosaicity have their bragg peak on that image. In which case, the start of the frame is < the peak and the end of the frame is > peak. The minimum bound on sigma_m is therefore zero.

**Comment by graeme-winter** [comment] 2017-05-24 13:20
For these data ipmosflm method seems pretty reasonable

```
Graemes-MBP-5:thaum graeme$ for dir in [0-9]; do cd $dir; bash ../runit.sh; cd - ; done
mosaic 0.20
image width 0.15
/Users/graeme/Projects/mosaic/thaum
mosaic 0.20
image width 0.05
/Users/graeme/Projects/mosaic/thaum
mosaic 0.20
image width 0.10
/Users/graeme/Projects/mosaic/thaum
mosaic 0.25
image width 0.20
/Users/graeme/Projects/mosaic/thaum
mosaic 0.20
image width 0.25
/Users/graeme/Projects/mosaic/thaum
```

**Comment by graeme-winter** [comment] 2017-05-24 13:20
#ooops close sorry :(

**Comment by jmp1985** [comment] 2017-05-24 14:02
Hi Graeme. How does the updated code I committed compare?

**Comment by graeme-winter** [comment] 2017-05-24 14:06
Please could you remind me how best to test?

**Comment by jmp1985** [comment] 2017-05-24 14:19
you should be able to use sigma_m_algorithm=extended in dials.integrate or dials.create_profile_model

**Comment by graeme-winter** [comment] 2017-05-24 14:34
OK, even default mosaic estimate looked reasonable...

```
Graemes-MBP-5:thaum graeme$ for f in */cp.log ; do grep 'Sigma M' $f | tail -3; done
Sigma M: 0.093957
Sigma M: 0.099994
Sigma M: 0.106587
Sigma M: 0.085798
Sigma M: 0.098680
Sigma M: 0.102164
Sigma M: 0.090649
Sigma M: 0.093056
Sigma M: 0.099909
Sigma M: 0.090577
Sigma M: 0.097290
Sigma M: 0.100084
Sigma M: 0.090390
Sigma M: 0.093234
Sigma M: 0.105022
```

(this is with P1)

**Comment by graeme-winter** [comment] 2017-05-24 14:35
Extended gave about the same answer

```
Graemes-MBP-5:thaum graeme$ for f in */cpe.log ; do grep 'Sigma M' $f | tail -3; done
Sigma M: 0.093957
Sigma M: 0.099994
Sigma M: 0.106587
Sigma M: 0.085798
Sigma M: 0.098680
Sigma M: 0.102165
Sigma M: 0.090649
Sigma M: 0.093056
Sigma M: 0.099910
Sigma M: 0.090577
Sigma M: 0.097290
Sigma M: 0.100084
Sigma M: 0.090390
Sigma M: 0.093234
Sigma M: 0.105022
```

Script

export run=`basename $PWD`
export template=/Users/graeme/data/strategy_image_width/Th_3_${run}_
```
dials.import ${template}*cbf allow_multiple_sweeps=true
dials.find_spots datablock.json
dials.index datablock.json strong.pickle
dials.create_profile_model experiments.json indexed.pickle | tee cp.log
dials.create_profile_model experiments.json indexed.pickle sigma_m_algorithm=extended | tee cpe.log

		   
```

**Comment by rjgildea** [comment] 2017-05-24 14:38
Is this for single (screening) images or an entire dataset?

**Comment by graeme-winter** [comment] 2017-05-24 14:39
3 x single images as listed above

**Comment by jmp1985** [comment] 2017-05-24 14:40
In that case, both basic and extended will give the same answer. extended will give better answers when you have an oscillation.

**Comment by graeme-winter** [comment] 2017-05-24 14:41
It is a rotation, 0.(something) degrees but not adjacent images, at 0, 45, 90

**Comment by graeme-winter** [comment] 2017-05-24 14:51
OK, looks like it could well be fixed - @rjgildea guess one for you to close if so

**Comment by rjgildea** [comment] 2017-05-24 14:57
Running xia2.strategy with:
```
module load dials/latest
module load best/4.1.0
xia2.strategy min_images=1 multi_sweep_indexing=True profile_fitting=False strategy.phil index.method=auto trust_beam_centre=True failover=True image=/dls/i04/data/2017/cm16781-2/gw/20170512/Thaumat/Th_3/Th_3_2_0001.cbf
```
etc.:
```
$ grep Mosaic /dls/i04/data/2017/cm16781-2/processing/rjgildea/20170512/Thaumat/Th_3/Th_3_*/xia2strategy/xia2.strategy.txt
/dls/i04/data/2017/cm16781-2/processing/rjgildea/20170512/Thaumat/Th_3/Th_3_2_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.076 < 0.076 < 0.076
/dls/i04/data/2017/cm16781-2/processing/rjgildea/20170512/Thaumat/Th_3/Th_3_4_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.074 < 0.074 < 0.074
/dls/i04/data/2017/cm16781-2/processing/rjgildea/20170512/Thaumat/Th_3/Th_3_4_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.083 < 0.083 < 0.083
/dls/i04/data/2017/cm16781-2/processing/rjgildea/20170512/Thaumat/Th_3/Th_3_4_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.079 < 0.079 < 0.079
/dls/i04/data/2017/cm16781-2/processing/rjgildea/20170512/Thaumat/Th_3/Th_3_5_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.076 < 0.076 < 0.076
/dls/i04/data/2017/cm16781-2/processing/rjgildea/20170512/Thaumat/Th_3/Th_3_5_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.079 < 0.079 < 0.079
/dls/i04/data/2017/cm16781-2/processing/rjgildea/20170512/Thaumat/Th_3/Th_3_5_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.077 < 0.077 < 0.077
/dls/i04/data/2017/cm16781-2/processing/rjgildea/20170512/Thaumat/Th_3/Th_3_6_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.074 < 0.074 < 0.074
/dls/i04/data/2017/cm16781-2/processing/rjgildea/20170512/Thaumat/Th_3/Th_3_6_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.085 < 0.085 < 0.085
/dls/i04/data/2017/cm16781-2/processing/rjgildea/20170512/Thaumat/Th_3/Th_3_6_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.077 < 0.077 < 0.077
/dls/i04/data/2017/cm16781-2/processing/rjgildea/20170512/Thaumat/Th_3/Th_3_7_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.070 < 0.070 < 0.070
/dls/i04/data/2017/cm16781-2/processing/rjgildea/20170512/Thaumat/Th_3/Th_3_7_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.083 < 0.083 < 0.083
/dls/i04/data/2017/cm16781-2/processing/rjgildea/20170512/Thaumat/Th_3/Th_3_7_/xia2strategy/xia2.strategy.txt:Mosaic spread: 0.071 < 0.071 < 0.071
```

**Comment by graeme-winter** [comment] 2017-05-24 14:58
So is problem solved? Excellent

**Comment by jmp1985** [comment] 2017-05-24 14:59
In that case, I will close related tickets too.

**Closed** 2017-05-24 15:16 UTC
Labels: dials.integrate
