### ISSUE TITLE
Boost.Python.ArgumentError importing prototype nexus file

### ISSUE THREAD

**Issue by xen-0** [dials/dials#434] opened 2017-08-22 10:13 UTC
[vmxi_nxs.tar.gz](https://github.com/dials/dials/files/1241596/vmxi_nxs.tar.gz)
Contains `vmxi_nxs.nxs` and other hdf5 files representing data files from an eiger (although with much smaller datasets).

I'll accept that vmxi_nxs.nxs may not be fully conforming, but it's hard to proceed with fixing it when I have no feed back on what's actually wrong.

```
 dials.import /scratch/vmxi_nxs.nxs -v
DIALS 1.7.0-g232651d0
Using FormatNexus for /scratch/vmxi_nxs.nxs
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v1-7-0/build/../modules/dials/command_line/dials_import.py", line 734, in <module>
    halraiser(e)
  File "/dls_sw/apps/dials/dials-v1-7-0/build/../modules/dials/command_line/dials_import.py", line 732, in <module>
    script.run()
  File "/dls_sw/apps/dials/dials-v1-7-0/build/../modules/dials/command_line/dials_import.py", line 596, in run
    params, options = self.parser.parse_args(show_diff_phil=False)
  File "/dls_sw/apps/dials/dials-v1-7-0/modules/dials/util/options.py", line 783, in parse_args
    quick_parse=quick_parse)
  File "/dls_sw/apps/dials/dials-v1-7-0/modules/dials/util/options.py", line 515, in parse_args
    format_kwargs=format_kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-0/modules/dials/util/options.py", line 209, in __init__
    format_kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-0/modules/dials/util/options.py", line 264, in try_read_datablocks_from_images
    format_kwargs=format_kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-0/modules/cctbx_project/dxtbx/datablock.py", line 890, in from_filenames
    format_kwargs=format_kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-0/modules/cctbx_project/dxtbx/datablock.py", line 471, in __init__
    format_kwargs=format_kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-0/modules/cctbx_project/dxtbx/datablock.py", line 643, in _create_single_file_imageset
    format_kwargs=format_kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-0/modules/cctbx_project/dxtbx/format/FormatMultiImage.py", line 165, in get_imageset
    format_instance = Class(filenames[0], **format_kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-0/modules/cctbx_project/dxtbx/format/FormatNexus.py", line 35, in __init__
    FormatHDF5.__init__(self, image_file, **kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-0/modules/cctbx_project/dxtbx/format/FormatHDF5.py", line 16, in __init__
    Format.__init__(self, image_file, **kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-0/modules/cctbx_project/dxtbx/format/Format.py", line 183, in __init__
    self.setup()
  File "/dls_sw/apps/dials/dials-v1-7-0/modules/cctbx_project/dxtbx/format/Format.py", line 193, in setup
    self._start()
  File "/dls_sw/apps/dials/dials-v1-7-0/modules/cctbx_project/dxtbx/format/FormatNexus.py", line 79, in _start
    self._detector_model = DetectorFactory(detector, self._beam_model).model
  File "/dls_sw/apps/dials/dials-v1-7-0/modules/cctbx_project/dxtbx/format/nexus.py", line 1342, in __init__
    mu))
Boost.Python.ArgumentError: Please report this error to dials-support@lists.sourceforge.net: Python argument types in
    Panel.__init__(Panel, str, str, tuple, tuple, tuple, tuple, tuple, tuple, float, str, float)
did not match C++ signature:
    __init__(_object*, std::string type, std::string name, scitbx::af::tiny<double, 3ul> fast_axis, scitbx::af::tiny<double, 3ul> slow_axis, scitbx::af::tiny<double, 3ul> origin, scitbx::af::tiny<double, 2ul> pixel_size, scitbx::af::tiny<unsigned long, 2ul> image_size, scitbx::af::tiny<double, 2ul> trusted_range, double thickness, std::string material, boost::shared_ptr<dxtbx::model::PxMmStrategy> px_mm, double mu=0.0, std::string identifier='')
    __init__(_object*, std::string type, std::string name, scitbx::af::tiny<double, 3ul> fast_axis, scitbx::af::tiny<double, 3ul> slow_axis, scitbx::af::tiny<double, 3ul> origin, scitbx::af::tiny<double, 2ul> pixel_size, scitbx::af::tiny<unsigned long, 2ul> image_size, scitbx::af::tiny<double, 2ul> trusted_range, double thickness, std::string material, double mu=0.0, std::string identifier='')
    __init__(_object*)
```

**Comment by jmp1985** [comment] 2017-08-22 11:37
Hi Charles,

I'm currently at the IUCR so may not be able to look at this immediately, but if you can point me to the nexus file, I can have a look at what might be going on (and I'll try to add some more useful information for when it fails).

James


________________________________

**Comment by Anthchirp** [comment] 2017-08-22 11:39
file is linked to at top of ticket. Thanks for looking into thus & enjoy IUCr

**Comment by jmp1985** [comment] 2017-08-22 11:41
Sorry! I missed the link.

James

________________________________

**Comment by jmp1985** [comment] 2017-08-25 04:09
Hi Charles,

Sorry for the late reply. I've finally finished all my talks so I can concentrate on other things. However, the internet is pretty slow here so I'm having trouble downloading stuff.

Just out of interest, why aren't we using the output files provided by Dectris? We worked quite closely with them to ensure that they were writing out the file format that we wanted. Do we gain anything by rolling our own implementation?

If you go to this github package, there is a script (details in the readme file) which you can run against the Nexus file which checks to see if it implements the NXmx feature. It should also tell you what items are missing. This was a package started by Mark Basham and Tobias Richter at Diamond.

https://github.com/nexusformat/features

James

________________________________
From: Parkhurst, James (DLSLtd,RAL,LSCI)
Sent: 22 August 2017 12:41
To: dials/dials; dials/dials
Cc: Comment
Subject: RE: [dials/dials] Boost.Python.ArgumentError importing prototype nexus file (#434)

Sorry! I missed the link.

James

________________________________

**Comment by xen-0** [comment] 2017-09-07 10:14
The following contains files written on the beamline
[vmxi_omega.tar.gz](https://github.com/dials/dials/files/1284308/vmxi_omega.tar.gz)

omega_300.nxs is the master file, and validates against NXmx, and displays the problem described in the issue.

(I would compress with xz, which compresses much better, but GitHub won't allow it)

**Comment by graeme-winter** [comment] 2017-09-07 11:07
Verified w/1.7.1 release:

```
[gw56@ws133 omega]$ dials.import omega_300.nxs 
DIALS 1.7.1-g93fc14f4-release
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v1-7-1/build/../modules/dials/command_line/dials_import.py", line 734, in <module>
    halraiser(e)
  File "/dls_sw/apps/dials/dials-v1-7-1/build/../modules/dials/command_line/dials_import.py", line 732, in <module>
    script.run()
  File "/dls_sw/apps/dials/dials-v1-7-1/build/../modules/dials/command_line/dials_import.py", line 596, in run
    params, options = self.parser.parse_args(show_diff_phil=False)
  File "/dls_sw/apps/dials/dials-v1-7-1/modules/dials/util/options.py", line 783, in parse_args
    quick_parse=quick_parse)
  File "/dls_sw/apps/dials/dials-v1-7-1/modules/dials/util/options.py", line 515, in parse_args
    format_kwargs=format_kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-1/modules/dials/util/options.py", line 209, in __init__
    format_kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-1/modules/dials/util/options.py", line 264, in try_read_datablocks_from_images
    format_kwargs=format_kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-1/modules/cctbx_project/dxtbx/datablock.py", line 890, in from_filenames
    format_kwargs=format_kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-1/modules/cctbx_project/dxtbx/datablock.py", line 471, in __init__
    format_kwargs=format_kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-1/modules/cctbx_project/dxtbx/datablock.py", line 643, in _create_single_file_imageset
    format_kwargs=format_kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-1/modules/cctbx_project/dxtbx/format/FormatMultiImage.py", line 165, in get_imageset
    format_instance = Class(filenames[0], **format_kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-1/modules/cctbx_project/dxtbx/format/FormatNexus.py", line 35, in __init__
    FormatHDF5.__init__(self, image_file, **kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-1/modules/cctbx_project/dxtbx/format/FormatHDF5.py", line 16, in __init__
    Format.__init__(self, image_file, **kwargs)
  File "/dls_sw/apps/dials/dials-v1-7-1/modules/cctbx_project/dxtbx/format/Format.py", line 183, in __init__
    self.setup()
  File "/dls_sw/apps/dials/dials-v1-7-1/modules/cctbx_project/dxtbx/format/Format.py", line 193, in setup
    self._start()
  File "/dls_sw/apps/dials/dials-v1-7-1/modules/cctbx_project/dxtbx/format/FormatNexus.py", line 79, in _start
    self._detector_model = DetectorFactory(detector, self._beam_model).model
  File "/dls_sw/apps/dials/dials-v1-7-1/modules/cctbx_project/dxtbx/format/nexus.py", line 1342, in __init__
    mu))
Boost.Python.ArgumentError: Please report this error to dials-support@lists.sourceforge.net: Python argument types in
    Panel.__init__(Panel, str, str, tuple, tuple, tuple, tuple, tuple, tuple, float, str, float)
did not match C++ signature:
    __init__(_object*, std::string type, std::string name, scitbx::af::tiny<double, 3ul> fast_axis, scitbx::af::tiny<double, 3ul> slow_axis, scitbx::af::tiny<double, 3ul> origin, scitbx::af::tiny<double, 2ul> pixel_size, scitbx::af::tiny<unsigned long, 2ul> image_size, scitbx::af::tiny<double, 2ul> trusted_range, double thickness, std::string material, boost::shared_ptr<dxtbx::model::PxMmStrategy> px_mm, double mu=0.0, std::string identifier='')
    __init__(_object*, std::string type, std::string name, scitbx::af::tiny<double, 3ul> fast_axis, scitbx::af::tiny<double, 3ul> slow_axis, scitbx::af::tiny<double, 3ul> origin, scitbx::af::tiny<double, 2ul> pixel_size, scitbx::af::tiny<unsigned long, 2ul> image_size, scitbx::af::tiny<double, 2ul> trusted_range, double thickness, std::string material, double mu=0.0, std::string identifier='')
    __init__(_object*)
```

different error w/personal source

```
dials.import omega_300.nxs 
DIALS 1.dev.1644-gece3cbc
Sorry: Unable to handle the following arguments:
  omega_300.nxs
```

**Comment by graeme-winter** [comment] 2017-09-07 11:15
Possibly I cannot count well, but it looks like the argument error is not right: the second __init__ C++ seems to match the call :thinking:

**Comment by xen-0** [comment] 2017-09-07 11:31
I believe it does - that was the point at which I stopped my analysis and opened the issue.

**Comment by graeme-winter** [comment] 2017-09-07 14:33
OK, now reproduced w/personal source following HDF5 update

**Comment by graeme-winter** [comment] 2017-09-07 14:35
Debug by print ++ helpfu

('Pixel', '/entry/instrument/eiger', (0.0, 1.0, 0.0), (-1.0, -0.0, 0.0), (array([ 0.]), array([ 0.]), array([ 700.008])), (0.075, 0.075), (2070, 2167), (-1, 4096.0), 0.45, 'Si', 0.013311391967204392)

some of these not tuple of numbers ;)

**Comment by graeme-winter** [comment] 2017-09-07 14:45
There are values in here stored as length 1 arrays rather than scalars => type errors occuring

Can work around or fix;

**Comment by graeme-winter** [comment] 2017-09-07 15:17
General mish-mash of types which are not what we expect - not wrong, just different

Working now will try to collate once I have $something working

**Comment by graeme-winter** [comment] 2017-09-08 08:21
OK, got it: the dependency is first on sample position them omega (which may be truth) 

Therefore have to search tree for first rotation which is rotating...

**Comment by graeme-winter** [comment] 2017-09-08 09:24
Closing now, since this no longer crashes (and identified some important fixes)

#todo get canonical example of nxmx file

**Closed by graeme-winter** 2017-09-08 09:24 UTC
