### ISSUE TITLE
dials.image_viewer cannot open datablock.json from dials.stills_process

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#226] opened 2016-10-03 09:04 UTC
I am processing datasets from SACLA by `dials.stills_process`. I found two issues.
## What I did

For this test, I am working on run266702-0.h5 avaialble at CXIDB http://www.cxidb.org/data/33/Raw_Files/.
Images are in a single hdf5 file and handled by my own dxtbx class.
(https://gist.github.com/biochem-fan/c1a014e2ad114457b28b; I will commit this to cctbx once fully tested.)

With the following phil file, processing seems to work:

```
indexing {
    known_symmetry {
        space_group = P43212
        unit_cell = 78.9 78.9 38.1 90 90 90
    }
    method = real_space_grid_search
    refinement_protocol.d_min_start = 2.2
}

spotfinder {
    filter.min_spot_size = 2
}

refinement {
    parameterisation {
        beam.fix = all
        detector.fix_list = Dist,Tau1
        auto_reduction {
            action = fix
            min_nref_per_parameter = 1
        }
        crystal {
            unit_cell {
                restraints {
                    tie_to_target {
                        values = 78.9,78.9,38.1,90,90,90
                        sigmas = 1,1,1,0,0,0
                        apply_to_all = True
                    }
                }
            }
        }
    }
}

integration {
    integrator = stills
    profile.fitting = False
    background {
        algorithm = simple
        simple {
            model.algorithm = linear2d
            outlier.algorithm = tukey
        }
    }
}
profile {
    gaussian_rs {
        min_spots.overall = 0
    }   
}
```

(By the way, Aaron's article in CCN 2016 says `outlier.algorithm = mosflm` but it is no longer avaialble, is it?)

The spot RMSD is about 1 px and the index rate is about 50 % before any optimization.
## First problem

I tried to make sure the prediction is correct:

```
dials.image_viewer idx-run266702-0_201_datablock.json idx-run266702-0_201_integrated.pickle
```

This does not work, saying

```
Traceback (most recent call last):
  File "/mnt/wd_storage/prog/dials/build/../modules/dials/command_line/image_viewer.py", line 183, in <module>
    runner()
  File "/mnt/wd_storage/prog/dials/build/../modules/dials/command_line/image_viewer.py", line 117, in __call__
    self.view()
  File "/mnt/wd_storage/prog/dials/build/../modules/dials/command_line/image_viewer.py", line 124, in view
    crystals=self.crystals)
  File "/mnt/wd_storage/prog/dials/modules/dials/util/spotfinder_wrap.py", line 30, in display
    self.frame.add_file_name_or_data(chooser_wrapper(imageset, idx))
  File "/mnt/wd_storage/prog/dials/modules/cctbx_project/rstbx/slip_viewer/frame.py", line 21, in __init__
    self.path = os.path.basename(image_set.get_path(index))
  File "/mnt/wd_storage/prog/dials/modules/cctbx_project/dxtbx/imageset.py", line 716, in get_path
    return self.reader().get_path(self._image_index(index))
  File "/mnt/wd_storage/prog/dials/modules/cctbx_project/dxtbx/imageset.py", line 732, in _image_index
    raise IndexError('Index out of range')
IndexError: Index out of range
```

datablock.json says

```
"image": 200
```

I think the logic of `ImageSet`'s `_image_index` is wrong. It says

```
    elif index < 0 or index >= len(self._indices):
      raise IndexError('Index out of range')
```

but in this case, `index` is 201 and `self._indices` is [201], not [0, 1, 2, ..., 201].
## Second problem

If I import the whole imageset, image viewer works just fine.

```
dials.import run266702-0.h5
dials.image_viewer datablock.json
```

But if I combine this `dabablock.json` with the `indexed` or `integrated` pickle,

```
dials.image_viewer datablock.json idx-run266702-0_201_indexed.pickle
dials.image_viewer datablock.json idx-run266702-0_201_integrated.pickle
```

spots are displayed on the first image, not the 202-nd image. 
(Note: file names are 0-indexed while the viewer is 1-indexed).

This is probably because the z coordinate of all spots are near 0.

**Comment by phyy-nx** [comment] 2016-10-06 17:03
Nigel and I have updated the CCN article to change mosflm to plane.  Thanks!

**Comment by biochem-fan** [comment] 2016-10-12 12:57
Hi Richard,

Everything you need is online:

- run266702-0.h5 avaialble at CXIDB: http://www.cxidb.org/data/33/Raw_Files/
- dxtbx class for SACLA MPCCD: https://gist.github.com/biochem-fan/c1a014e2ad114457b28b
  (replace the file in dxtbx/format by the file above)
- index.phil (in my first post)

Then run:
```
dials.stills_process run266702-0.h5 index.phil
```

**Comment by rjgildea** [comment] 2016-10-12 13:06
I was kind of hoping I would be able to easily reproduce with a few image files, and not a 0.6Gb download... (also a pointed reminder to @phyy-nx that we still really need a dials.stills_process test case!)

**Comment by phyy-nx** [comment] 2016-10-12 22:22
Richard, this issue is focused on HDF5 data (or more specifically, any
multi-image file).  We have no NeXus files or SACLA datasets in
dials_regression (or SLAC XTC streams for that matter).  Checking in one of
the Dectris datasets to dials_regression seems clearly inappropriate.  The
ideal test case would be a file with only two images.  I recently tried
using python/h5py to trim down an existing HDF5 file but I didn't figure
out the right incantation.  It would be worth trying again.

-Aaron

**Comment by biochem-fan** [comment] 2016-10-13 02:17
Hi Aaron,

Deleting entries in an existing HDF5 file does not reduce the file size. You have to run `h5repack` or copy some entries to a new file. 

I uploaded the first four images from run266702-0 (just 8 MB) to dials_regression/image_examples/SACLA_MPCCD_Cheetah.

**Comment by graeme-winter** [comment] 2016-10-13 11:45
Folks

Good to have added a test case but someone needs to add support for it as well to dxtbx (i.e. make it work right)

ATM getting 


Error: the following jobs returned non-zero exit codes or suspicious stderr output:

libtbx.python "/Users/graeme/svn/cctbx/modules/dials_regression/test.py" [FAIL]
  Time: 80.17
  Return code: 1
  OKs: 0
  Standard error:
    Traceback (most recent call last):
      File "/Users/graeme/svn/cctbx/modules/dials_regression/test.py", line 139, in <module>
        else: run()
      File "/Users/graeme/svn/cctbx/modules/dials_regression/test.py", line 75, in run
        I = SlipViewerImageFactory(fk)
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/rstbx/slip_viewer/slip_viewer_image_factory.py", line 11, in SlipViewerImageFactory
        return defaultImageFactory(filename)
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/iotbx/detectors/__init__.py", line 73, in ImageFactory
        format_instance = Registry.find(filename)
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/format/Registry.py", line 81, in find
        raise IOError, 'no format support found for %s' % image_file
    IOError: no format support found for /Users/graeme/svn/cctbx/modules/dials_regression/image_examples/SACLA_MPCCD_Cheetah/README

i.e. would be nice to have the builds pass too

Best wishes Graeme

**Comment by phyy-nx** [comment] 2016-10-13 11:55
Hi Graeme, I'm going to check in the dxtbx class Takanori sent into dxtbx
as soon as I can.  At the NIAC now.

-Aaron

**Comment by biochem-fan** [comment] 2016-10-13 12:06
And it seems that the test tries to read all files under the directory. Where should I put the README?

**Comment by rjgildea** [comment] 2016-10-13 12:13
test.py now skips README files, now get:

```
READING image_examples/SACLA_MPCCD_Cheetah/run266702-0-subset.h5       
Traceback (most recent call last):
  File "/home/hko55533/software/cctbx/modules/dials_regression/test.py", line 140, in <module>
    else: run()
  File "/home/hko55533/software/cctbx/modules/dials_regression/test.py", line 76, in run
    I = SlipViewerImageFactory(fk)
  File "/home/hko55533/software/cctbx/modules/cctbx_project/rstbx/slip_viewer/slip_viewer_image_factory.py", line 11, in SlipViewerImageFactory
    return defaultImageFactory(filename)
  File "/home/hko55533/software/cctbx/modules/cctbx_project/iotbx/detectors/__init__.py", line 75, in ImageFactory
    return instance.get_detectorbase()
  File "/home/hko55533/software/cctbx/modules/cctbx_project/dxtbx/format/FormatHDF5SaclaMPCCD.py", line 236, in get_detectorbase
    raise RuntimeError('Overload!')
RuntimeError: Overload!
```

**Comment by biochem-fan** [comment] 2016-10-13 12:19
It should not happen with the latest version; please wait Aaron's commit.

**Comment by phyy-nx** [comment] 2016-10-13 16:02
The format class has been committed and I verified dials.stills_process
process.phil
dials_regression/image_examples/SACLA_MPCCD_Cheetah/run266702-0-subset.h5
works.  I'll make this into a test next.  In the meantime, this issue can
now be debugged.

Haven't run test.py yet.

**Comment by rjgildea** [comment] 2016-10-14 08:52
I don't think this bug is specific to dials.image_viewer, perhaps @jmp1985 could comment further on whether the following should be expected to work?

```
$ dials.stills_process $(libtbx.find_in_repositories
$ dials_regression/image_examples/SACLA_MPCCD_Cheetah/run266702-0-subset.h5) process.phil
```

```
$ dials.python
>>> from dxtbx.serialize import load
>>> datablock = load.datablock('idx-run266702-0-subset_2_datablock.json')[0]
>>> imageset = datablock.extract_imagesets()[0]
>>> path = imageset.get_path(imageset.indices()[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/imageset.py", line 716, in get_path
    return self.reader().get_path(self._image_index(index))
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/imageset.py", line 732, in _image_index
    raise IndexError('Index out of range')
IndexError: Index out of range
```

**Comment by rjgildea** [comment] 2016-10-14 09:21
I have added a simpler failing test to dxtbx that demonstrates what I think is the problem:

https://sourceforge.net/p/cctbx/code/25576/

@jmp1985 please could you take a look at this?

**Comment by rjgildea** [comment] 2016-10-14 09:23
I think this is one of the same bugs that was reported in #199

**Comment by biochem-fan** [comment] 2016-10-21 15:34
Hi Richard, get_path() issue can be solved by my patch on #227. In addition to that, I think lines below at `spotfinder_wrap.py` should be:

```python
    for imageset in imagesets:
      for i in xrange(len(imageset.indices())):
        self.frame.add_file_name_or_data(chooser_wrapper(imageset, i))
    self.frame.load_image(chooser_wrapper(imagesets[0],0))
```
https://github.com/dials/dials/blob/master/util/spotfinder_wrap.py#L30

That is, images should be indexed **not** by the true index within a multi-event file, but by the index within the imageset. The `ImageSet` class translates indices.

I confirmed that the followings work for the outputs from `dials.stills_process`:
```
dials.image_viewer idx_filename_0000NN_datablock.json idx_filename_0000NN_integrated.pickle
dials.predict idx_filename_0000NN_refined_experiments.json 
dials.image_viewer idx_filename_0000NN_datablock.json predicted.pickle
```

However, the followings does **not** work.
```
dials.image_viewer idx_filename_0000NN_refined_experiments.json idx_filename_0000NN_integrated.pickle
dials.image_viewer idx_filename_0000NN_refined_experiments.json predicted.pickle
```
These try to call 
```
frame_numbers = scan.get_array_index_from_angle(phi * to_degrees)
```
at https://github.com/dials/dials/blob/master/util/spotfinder_frame.py#L1036 and die.

```
dials.image_viewer idx_filename_0000NN_datablock.json idx_filename_0000NN_strong.pickle
```
also does **not** work, because the z coordinates of `xyzobs.px.value` are not 0, but the image number in `strong.pickle`. In contrast, the z coordinates of  `xyzcal.px` in `integrated.pickle` and `predicted.pickle` are 0, so  these work fine for `datablock.json`. I don't know why they don't work well when combined with `experiments.json`.

**Comment by jmp1985** [comment] 2016-10-25 14:03
OK, I'm trying to figure this all out. 

1. I think Takanori is correct; spotfinder_wrap needs to be modified. I propose the following patches (@rjgildea does this seem sensible?):

```
	$git diff dials/util/spotfinder_wrap.py
	@@ -24,11 +24,12 @@ class spot_wrapper(object):

	     i = 0
	     for imageset in imagesets:
	-      for idx in imageset.indices():
	+      for idx in range(len(imageset.indices())):
		 i += 1
		 #print i
		 self.frame.add_file_name_or_data(chooser_wrapper(imageset, idx))
	-    idx = imagesets[0].indices()[0]
	+    #idx = imagesets[0].indices()[0]
	+    idx = 0
	     self.frame.load_image(chooser_wrapper(imagesets[0],idx))
	 
	     app.MainLoop()


	$ svn diff cctbx_project/rstbx/slip_viewer/frame.py
	@@ -20,7 +20,8 @@
	     self.image_set = image_set
	     self.path = os.path.basename(image_set.get_path(index))
	     self.full_path = image_set.get_path(index)
	-    self.index = index
	+    self.index = self.image_set.indices()[index]
	+    self.frame_index = index
	     self._raw_data = None
	 
	   def __str__(self):
	@@ -31,11 +32,11 @@
	   def get_beam(self):  return self.image_set.get_beam()
	   def get_mask(self, goniometer_shadow_mask=False):
	     return self.image_set.get_mask(
	-      self.index, goniometer_shadow_mask=goniometer_shadow_mask)
	+      self.frame_index, goniometer_shadow_mask=goniometer_shadow_mask)
	 
	   def get_raw_data(self):
	     if self._raw_data is None:
	-      self._raw_data = self.image_set[self.index]
	+      self._raw_data = self.image_set[self.frame_index]
	     return self._raw_data
	 
	   def set_raw_data(self, raw_data):
	@@ -42,10 +43,10 @@
	     self._raw_data = raw_data
	 
	   def get_detectorbase(self):
	-    return self.image_set.get_detectorbase(self.index)
	+    return self.image_set.get_detectorbase(self.frame_index)
	 
	   def show_header(self):
	-    return self.image_set.get_detectorbase(self.index).show_header()
	+    return self.image_set.get_detectorbase(self.frame_index).show_header()
```
	 

This allows dials.image_viewer idx-run266702-0-subset_00002_datablock.json idx-run266702-0-subset_00002_strong.pickle to run correctly.



I can confirm that the following fails in dials/util/spotfinder_frame.py. The imageset contains stills and therefore doesn't have a scan, which is causing the code to fail.

	dials.image_viewer idx_filename_0000NN_refined_experiments.json idx_filename_0000NN_integrated.pickle
	dials.image_viewer idx_filename_0000NN_refined_experiments.json predicted.pickle


Finally, the following works for me with the above patches

	dials.image_viewer idx_filename_0000NN_datablock.json idx_filename_0000NN_strong.pickle

**Comment by biochem-fan** [comment] 2016-10-25 15:23
Hi James, unfortunately your patch does not allow the following:

```
dials.image_viewer idx_filename_0000NN_datablock.json  idx_filename_0000NN_integrated.pickle
```

The z component of `xyzobs.px.value` in `strong.pickle`, which is the frame number, and the z component of `xyzcal.px` in `integrated.pickle` and `predicted.pickle`, which is always 0 for stills, should be made consistent. Your patch supports `strong.pickle` but not the others, while my patch vice versa. We can reset the z component of `xyzobs.px.value` to be 0 in `dials.stills_process` before writing `strong.pickle`. @phyy-nx , what do you think? Since `strong.pickle` is only for manual inspection, I think that is what to be modified.

**Comment by jmp1985** [comment] 2016-10-25 18:16
I'm trying to think what the proper behaviour should be. I suppose this is not an issue for sweeps because the whole dataset is processed each time. So the problem here is that spot finding is done on the whole imageset but integration is done on a subset (i.e. a single image). The z component of xyzobs.px.value originally referred to the coordinate in the 3D image volume; perhapes it should be image number instead which would solve the problem. Not sure if this would break anything else though!
________________________________

**Comment by jmp1985** [comment] 2016-10-25 18:23
Of course the coordinate in spot finding would also have to be image number as well.

________________________________
From: Parkhurst, James (DLSLtd,RAL,LSCI)
Sent: 25 October 2016 16:28
To: dials/dials; dials/dials
Cc: Mention
Subject: RE: [dials/dials] dials.image_viewer cannot open datablock.json from dials.stills_process (#226)

I'm trying to think what the proper behaviour should be. I suppose this is not an issue for sweeps because the whole dataset is processed each time. So the problem here is that spot finding is done on the whole imageset but integration is done on a subset (i.e. a single image). The z component of xyzobs.px.value originally referred to the coordinate in the 3D image volume; perhapes it should be image number instead which would solve the problem. Not sure if this would break anything else though!
________________________________

**Comment by biochem-fan** [comment] 2016-10-26 13:22
> spot finding is done on the whole imageset but integration is done on a subset (i.e. a single image).

In `dials.stills_process`, spot finding is done after imageset slicing, thus it also works on a single image. That is why I proposed setting the z component of `xyzobs.px.value` to be 0 in `dials.stills_process` before writing strong.pickle.

That being said, I agree that your idea to use the image number in `xyzobs.px.value` has an advantage. If we take this approach, we can run `dials.image_viewer images.h5 combined_integration.pickle` to see integration results of many frames within a multi-event file without re-launching the viewer many times (which is very slow with X11 forwarding over VPN).

**Comment by jmp1985** [comment] 2016-10-27 15:35
Hi Takanori,

Maybe for the moment setting the z component from spot finding to be zero would be the easiest fix and we can discuss what to do in the long term later on. There's this whole thing about array_range and image_range in dxtbx which has always caused problems and maybe we need to make a larger change.

James

________________________________

**Comment by biochem-fan** [comment] 2016-10-29 23:24
Hi James, 

I agree with you. I will add an option in `dials.stills_process` to set the z component to be 0. `dials.image_viewer` needs a fix in dials/util/spotfinder_wrap.py but not in rstbx/slip_viewer/frame.py.

**Closed** 2016-10-31 08:06 UTC
Labels: bug, dxtbx

**Comment by biochem-fan** [comment] 2016-10-31 08:08
Hi James,

I committed the fixes.

I had to reset the last two elements of `bbox` as well because the image viewer also looks at `bbox`.

https://github.com/dials/dials/blob/master/util/spotfinder_frame.py#L929
https://github.com/dials/dials/blob/master/util/spotfinder_frame.py#L1038

The integration result seems unaffected.
