### ISSUE TITLE
dials.scale: Value -nan can not be represented in the target integer type.

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#1245] opened 2020-04-27 07:52 UTC
```
$ dials.scale  '49_scaled.expt' '49_scaled.refl' 'nproc=4' 'model=physical' 'physical.decay_correction=True' 'physical.absorption_correction=False' 'physical.decay_interval=1.5' 'physical.scale_interval=1' 'full_matrix=False' 'error_model=basic' 'outlier_rejection=standard' 'reflection_selection.Isigma_range=2.000000,100000.000000' 'cut_data.d_min=19.9' 'output.unmerged_mtz=51_scaled_unmerged.mtz' 'output.merged_mtz=51_scaled.mtz' 'output.html=51_scaling.html' 'output.experiments=51_scaled.expt' 'output.reflections=51_scaled.refl'


Summary of cross-dataset reflection groups chosen (5 groups, 14 reflections):
+-----------------+------------+----------+-----+-----+-----+-----+-----+-----+-----+
| d-range         |   n_groups |   n_refl |   0 |   1 |   2 |   3 |   4 |   5 |   6 |
|-----------------+------------+----------+-----+-----+-----+-----+-----+-----+-----|
| 35.433 - 33.677 |          1 |        2 |   0 |   0 |   1 |   1 |   0 |   0 |   0 |
| 32.159 - 30.829 |          1 |        2 |   0 |   0 |   0 |   0 |   1 |   0 |   1 |
| 29.651 - 28.599 |          1 |        5 |   1 |   0 |   2 |   1 |   0 |   0 |   1 |
| 23.445 - 22.914 |          1 |        3 |   0 |   1 |   1 |   0 |   0 |   1 |   0 |
| 20.345 - 19.996 |          1 |        2 |   0 |   0 |   1 |   0 |   1 |   0 |   0 |
+-----------------+------------+----------+-----+-----+-----+-----+-----+-----+-----+
Summary of reflections chosen for minimisation from each dataset (14 total):
+--------------+------------------+----------------------+----------------------+--------------------+
| Dataset id   |     reflections  |   randomly selected  |   randomly selected  |   combined number  |
|              |    connected to  |         reflections  |         reflections  |     of reflections |
|              |   other datasets |       within dataset |      across datasets |                    |
|--------------+------------------+----------------------+----------------------+--------------------|
| 0            |                1 |                    0 |                    0 |                  1 |
| 1            |                1 |                    0 |                    0 |                  1 |
| 2            |                5 |                    2 |                    0 |                  5 |
| 3            |                2 |                    0 |                    0 |                  2 |
| 4            |                2 |                    0 |                    0 |                  2 |
| 5            |                1 |                    0 |                    0 |                  1 |
| 6            |                2 |                    0 |                    0 |                  2 |
| total        |               14 |                    2 |                    0 |                 14 |
+--------------+------------------+----------------------+----------------------+--------------------+
Completed configuration of MultiScaler. 

================================================================================

Components to be refined in this cycle for all datasets: scale, decay
Performing a round of scaling with an LBFGS minimizer. 

Error in function boost::math::round<double>(double): Value -nan can not be represented in the target integer type.
Traceback (most recent call last):
  File "/scratch/jenkins_agent/workspace/xia2_tests_python3/build_dials/modules/dials/algorithms/scaling/scaler.py", line 202, in _perform_scaling
    refinery.run()
  File "/scratch/jenkins_agent/workspace/xia2_tests_python3/build_dials/modules/dials/algorithms/refinement/engine.py", line 593, in run
    return self.run_lbfgs(curvatures=False)
  File "/scratch/jenkins_agent/workspace/xia2_tests_python3/build_dials/modules/dials/algorithms/refinement/engine.py", line 567, in run_lbfgs
    log=ref_log,
  File "/scratch/jenkins_agent/workspace/xia2_tests_python3/build_dials/modules/cctbx_project/scitbx/lbfgs/__init__.py", line 278, in run
    line_search)
  File "/scratch/jenkins_agent/workspace/xia2_tests_python3/build_dials/modules/cctbx_project/scitbx/lbfgs/__init__.py", line 131, in run_c_plus_plus
    f, g = target_evaluator.compute_functional_and_gradients()
  File "/scratch/jenkins_agent/workspace/xia2_tests_python3/build_dials/modules/dials/algorithms/refinement/engine.py", line 488, in compute_functional_and_gradients
    L, dL_dp, _ = self.compute_functional_gradients_and_curvatures()
  File "/scratch/jenkins_agent/workspace/xia2_tests_python3/build_dials/modules/dials/algorithms/scaling/scaling_refiner.py", line 234, in compute_functional_gradients_and_curvatures
    self._scaler.update_for_minimisation(self._parameters, block_id)
  File "/scratch/jenkins_agent/workspace/xia2_tests_python3/build_dials/modules/dials/algorithms/scaling/scaler.py", line 919, in update_for_minimisation
    self._update_for_minimisation(apm, block_id, calc_Ih=True)
  File "/scratch/jenkins_agent/workspace/xia2_tests_python3/build_dials/modules/dials/algorithms/scaling/scaler.py", line 926, in _update_for_minimisation
    apm_i, block_id
  File "/scratch/jenkins_agent/workspace/xia2_tests_python3/build_dials/modules/dials/algorithms/scaling/basis_functions.py", line 68, in calculate_scales_and_derivatives
    scales, derivatives = cls._calc_component_scales_derivatives(apm, block_id)
  File "/scratch/jenkins_agent/workspace/xia2_tests_python3/build_dials/modules/dials/algorithms/scaling/basis_functions.py", line 24, in _calc_component_scales_derivatives
    sdc = component["object"].calculate_scales_and_derivatives(block_id)
  File "/scratch/jenkins_agent/workspace/xia2_tests_python3/build_dials/modules/dials/algorithms/scaling/model/components/smooth_scale_components.py", line 257, in calculate_scales_and_derivatives
    self._normalised_values[block_id][0], self.value
  File "/scratch/jenkins_agent/workspace/xia2_tests_python3/build_dials/modules/dials/algorithms/scaling/model/components/smooth_scale_components.py", line 29, in value_weight
    result = super(GaussianSmoother1D, self).value_weight(x, value)
RuntimeError: Error in function boost::math::round<double>(double): Value -nan can not be represented in the target integer type.
```

happens in every other run of xia2 test `Test.regression.test_multiplex.test_proteinase_k_filter_deltacchalf`

**Comment by Anthchirp** [comment] 2020-04-27 07:53
files in `/dls/tmp/dials-1245`

**Comment by phyy-nx** [comment] 2020-04-29 19:08
Comment from @bkpoon: try without --fast-math?

**Comment by bkpoon** [comment] 2020-04-29 21:00
Yeah, `-ffast-math` makes nan behavior not well defined. For GCC, `-ffast-math` turns on `-ffinite-math-only`(https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html). For clang, `-ffast-math` may also break nan behavior (https://clang.llvm.org/docs/UsersManual.html#controlling-floating-point-behavior). Same with Visual Studio and `/fp:fast` (https://docs.microsoft.com/en-us/cpp/build/reference/fp-specify-floating-point-behavior?view=vs-2015).

**Comment by graeme-winter** [comment] 2020-05-11 09:05
Verified / reproduced.

**Comment by graeme-winter** [comment] 2020-05-11 09:11
Also on fruity computer -> unlikely to be related to GCC ffast-math (built with clang)

**Comment by graeme-winter** [comment] 2020-05-11 09:32
```
    SingleValueWeights value_weight(double x, const af::const_ref<double> values) {
      // use sparse storage as only naverage (default 3) values are non-zero
      vector<double> weight(nvalues);

      // normalised coordinate

      std::cout << x << "\t" << x0 << "\t" << spacing_ << std::endl;
      double z = (x - x0) / spacing_;
```

in `gaussian_smoother.h`

-> 

```
0	0	0
```

will end up with rather an ill defined value

**Comment by graeme-winter** [comment] 2020-05-11 09:49
Given that `x0` and `spacing_` both have NULL values I would infer we have a fundamental design issue buried in here somewhere.

**Comment by graeme-winter** [comment] 2020-05-11 09:56
<aha!> 

```
        self._smoother = GaussianSmoother1D(
            phi_range_deg, self.nparam_to_val(self._n_params)
        )
```

`phi_range_deg=[0, 0]` 🙄

**Comment by graeme-winter** [comment] 2020-05-11 10:35
Oh wait, this is really simple

Command line has `d_min=19.9` i.e. throw away almost all the reflections

If this is removed, 

```
                ----------Resolution cutoff estimates----------                

  resolution of all data          :   4.110
  based on CC(1/2) >= 0.33        :   4.629
  based on mean(I/sigma) >= 2.0   :   4.110
  based on R-merge < 0.5          :   4.110
  based on R-meas < 0.5           :   4.110
  based on completeness >= 90%    : (use all data)
  based on completeness >= 50%    :   4.110

``` 

and program works - @Anthchirp where did this job come from? The issue is upstream however `dials.scale` should cope more gracefully here

**Comment by graeme-winter** [comment] 2020-05-11 11:00
```
pytest --regression --regression-full Test/regression/test_multiplex.py::test_proteinase_k_filter_deltacchalf
```

is the upstream error source - have run ~ 10 times, failed to reproduce error

**Comment by Anthchirp** [comment] 2020-05-11 11:17
Did you try that on a real computer?

**Comment by graeme-winter** [comment] 2020-05-11 11:44
Yes, on com99-01

**Comment by graeme-winter** [comment] 2020-05-11 11:53
Perhaps useful datum is the mismatch in object size:

```
=============================== warnings summary ===============================
Test/regression/test_multiplex.py::test_proteinase_k_filter_deltacchalf
  /dls/science/users/gw56/git/conda_base/lib/python3.6/site-packages/numpy/matrixlib/defmatrix.py:71: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
    return matrix(data, dtype=dtype, copy=False)

Test/regression/test_multiplex.py::test_proteinase_k_filter_deltacchalf
Test/regression/test_multiplex.py::test_proteinase_k_filter_deltacchalf
Test/regression/test_multiplex.py::test_proteinase_k_filter_deltacchalf
  /dls/science/users/gw56/git/conda_base/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
    return f(*args, **kwds)
```

**Comment by Anthchirp** [comment] 2020-05-11 12:24
Weird, because on Jenkins this test has a very high failure rate:
https://jenkins.diamond.ac.uk/view/DIALS-monitor/job/xia2_tests_python3/lastCompletedBuild/testReport/junit/Test.regression/test_multiplex/test_proteinase_k_filter_deltacchalf/history/

**Comment by graeme-winter** [comment] 2020-05-11 13:12
OK, so running on the same machine (ws133) with the same platform (Python 3) several times I do not reproduce this _in isolation_

**Comment by Anthchirp** [comment] 2020-05-14 14:15
moved the xia2-specifics of the failure into xia2/xia2#454, the issue reported here may be independent.

**Comment by jbeilstenedmands** [comment] 2020-08-07 07:10
To easily reproduce: `dials.scale $(dials.data get -q l_cysteine_4_sweeps_scaled)/scaled_35.* d_min=6.8 min_isigi=116.3`

Looking into a fix for this now.

**Closed** 2020-08-07 10:07 UTC
