### ISSUE TITLE
Importing OptionParser calls fork()?

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#720] opened 2019-03-03 21:28 UTC
While trying to use `dev.mpi.cluster_two_merge_cs`, I noticed that importing `OptionParser` _after_ `mpi4py` causes a problem. The system (SACLA HPC system) uses OpenMPI 2.0.0.

Source:
```python
from mpi4py import MPI
print 'MPI imported'
print MPI.COMM_WORLD.Get_rank()

from dials.util.options import OptionParser
print 'OptionParser imported'
```

Output:
```
$ mpirun -n 2 dials.python mpitest.py
after mpi import
0
after mpi import
1
--------------------------------------------------------------------------
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[3456,1],0] (PID 54613)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
OptionParser imported
OptionParser imported
[xhpcfep02:54606] 1 more process has sent help message help-opal-runtime.txt / opal_init:warn-fork
[xhpcfep02:54606] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

If I reverse the order, the code works fine.

```python
from dials.util.options import OptionParser
print 'OptionParser imported'

from mpi4py import MPI
print 'MPI imported'
print MPI.COMM_WORLD.Get_rank()
```

Interestingly, `strace dials.python -c 'from dials.util.options import OptionParser'` does NOT say it called `fork()` or `system()`.

**Comment by asmit3** [comment] 2019-03-04 06:39
At SACLA we have used OpenMPI 3+ in order to avoid this specific problem. Would love to know what is going on.  Prior experience with older OpenMPI versions suggest there are issues with distributing the workload among MPI ranks leading to each rank ending up doing the same (and entire) work independently. My hunch is it might be a compatibility issue between the mpi4py version and the openmpi version.

**Comment by biochem-fan** [comment] 2019-03-04 07:54
@asmit3, thanks for information. In the test above, the printed ranks are 0 and 1, which means that 'each rank ending up doing the same (and entire) work independently' is not the case here.

**Comment by Anthchirp** [comment] 2019-03-04 07:58
dials.util.options only does a few imports, only one of which leaves the standard Python library.
Could you try cutting down ```options.py``` to a minimal example showing the issue?
Then do the same for ```dials/util/__init__.py```.

**Comment by biochem-fan** [comment] 2019-03-04 08:55
Surprisingly, `tqdm` is the cause.

```python
from mpi4py import MPI
print 'after mpi import'
print MPI.COMM_WORLD.Get_rank()

from tqdm import tqdm
print 'tqdm imported'
```

**Comment by graeme-winter** [comment] 2019-03-04 09:05
Wait, what? A progress bar can break MPI? 😵 😱

**Comment by Anthchirp** [comment] 2019-03-04 09:13
best guess: the locking initialisation code in tqdm.
This seems to have been rewritten in more recent versions of tqdm.
Can you reproduce this with tqdm 4.31.1?
if still an issue in 4.31.1 -> https://github.com/tqdm/tqdm/issues
if fixed in 4.31.1 -> assign ticket to @ndevenish to check if we can update tqdm versions

**Comment by biochem-fan** [comment] 2019-03-04 14:11
Yes, the issue persists with 4.31.1. I reported this to https://github.com/tqdm/tqdm/issues/691.

**Comment by ndevenish** [comment] 2019-03-04 20:56
hmm, I don't think tqdm should be used unless something explicitly needs it. I'll have a dig into the usage.

**Comment by biochem-fan** [comment] 2020-10-08 17:33
@ndevenish This problem was fixed in the latest version of tqdm (see tqdm/tqdm#691).

**Comment by ndevenish** [comment] 2020-10-09 10:29
This doesn't seem to happen with openmpi 4, which is what conda installs, so I can't check, but am happy to update our tqdm dependence in any case.

**Comment by ndevenish** [comment] 2020-10-09 10:37
Okay, it looks like we're always pulling whatever latest version conda-forge has now, so this should fix itself in the next releases (although not there are any cases where we use <OpenMPI 4 now anyway). thanks!

**Closed by ndevenish** 2020-10-09 10:37 UTC
Labels: validate
