### ISSUE TITLE
dials.index: please do not delete scan and goniometer for still images

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1030] opened 2019-11-21 16:01 UTC
If we record a grid scan at multiple angles would be useful to keep this information around after indexing - right now the scan and goniometer are deliberately deleted. 

Propose we keep them iff the input experiment->imageset is an ImageSequence not ImageSet.

Current output looks like:

```
Experiment 7:
Detector:
Panel:
  name: /entry/instrument/detector
  type: SENSOR_PAD
  identifier: 
  pixel_size:{0.075,0.075}
  image_size: {4148,4362}
  trusted_range: {-1,65535}
  thickness: 0.45
  material: Si
  mu: 22.0599
  gain: 1
  pedestal: 0
  fast_axis: {0.999992,-0.00122992,-0.00377055}
  slow_axis: {-0.00125372,-0.999979,-0.00631484}
  origin: {-155.863,168.099,-151.551}
  distance: 153.195
  pixel to millimeter strategy: ParallaxCorrectedPxMmStrategy
    mu: 22.0599
    t0: 0.45


Max resolution (at corners): 1.869481
Max resolution (inscribed):  2.304973

Beam:
    wavelength: 1.77118
    sample to source direction : {-0.000611717,-0,1}
    divergence: 0
    sigma divergence: 0
    polarization normal: {0,1,0}
    polarization fraction: 0.999

Beam centre: 
    mm: (156.17,167.91)
    px: (2082.24,2238.81)

Crystal:
    Unit cell: (68.07(2), 68.07(2), 68.04(3), 109.31(3), 109.57(3), 109.553(16))
    Space group: P 1
    U matrix:  {{ 0.1011, -0.9897,  0.1014},
                {-0.7773, -0.1422, -0.6129},
                { 0.6210, -0.0168, -0.7837}}
    B matrix:  {{ 0.0147,  0.0000,  0.0000},
                { 0.0052,  0.0156,  0.0000},
                { 0.0090,  0.0090,  0.0180}}
    A = UB:    {{-0.0028, -0.0145,  0.0018},
                {-0.0177, -0.0077, -0.0110},
                { 0.0020, -0.0073, -0.0141}}
Experiment 8:
Detector:
Panel:
  name: /entry/instrument/detector
  type: SENSOR_PAD
  identifier: 
  pixel_size:{0.075,0.075}
  image_size: {4148,4362}
  trusted_range: {-1,65535}
  thickness: 0.45
  material: Si
  mu: 22.0599
  gain: 1
  pedestal: 0
  fast_axis: {0.999992,-7.79475e-06,-0.00401508}
  slow_axis: {-3.00879e-05,-0.999985,-0.00555233}
  origin: {-156.084,167.873,-151.584}
  distance: 153.14
  pixel to millimeter strategy: ParallaxCorrectedPxMmStrategy
    mu: 22.0599
    t0: 0.45


Max resolution (at corners): 1.869864
Max resolution (inscribed):  2.304584

Beam:
    wavelength: 1.77118
    sample to source direction : {-0.000479666,-0,1}
    divergence: 0
    sigma divergence: 0
    polarization normal: {0,1,0}
    polarization fraction: 0.999

Beam centre: 
    mm: (156.16,167.87)
    px: (2082.19,2238.33)

Crystal:
    Unit cell: (68.005(19), 68.092(17), 68.09(2), 109.334(15), 109.543(15), 109.531(8))
    Space group: P 1
    U matrix:  {{ 0.1026, -0.9895,  0.1017},
                {-0.7773, -0.1435, -0.6125},
                { 0.6207, -0.0162, -0.7839}}
    B matrix:  {{ 0.0147,  0.0000,  0.0000},
                { 0.0052,  0.0156,  0.0000},
                { 0.0090,  0.0090,  0.0180}}
    A = UB:    {{-0.0027, -0.0145,  0.0018},
                {-0.0177, -0.0077, -0.0110},
                { 0.0020, -0.0073, -0.0141}}
```

for input 

```
Experiment 7:
Detector:
Panel:
  name: /entry/instrument/detector
  type: SENSOR_PAD
  identifier: 
  pixel_size:{0.075,0.075}
  image_size: {4148,4362}
  trusted_range: {-1,65535}
  thickness: 0.45
  material: Si
  mu: 22.0599
  gain: 1
  pedestal: 0
  fast_axis: {1,0,0}
  slow_axis: {0,-1,0}
  origin: {-156.085,167.598,-152.875}
  distance: 152.875
  pixel to millimeter strategy: ParallaxCorrectedPxMmStrategy
    mu: 22.0599
    t0: 0.45


Max resolution (at corners): 1.877967
Max resolution (inscribed):  2.295200

Beam:
    wavelength: 1.77118
    sample to source direction : {0,0,1}
    divergence: 0
    sigma divergence: 0
    polarization normal: {0,1,0}
    polarization fraction: 0.999

Beam centre: 
    mm: (156.09,167.60)
    px: (2081.13,2234.64)

Scan:
    image range:   {8,8}
    oscillation:   {0,0}
    exposure time: 0

Goniometer:
    Rotation axis:   {1,-0.0024998,0.00559999}
    Fixed rotation:  {1,0,0,0,1,0,0,0,1}
    Setting rotation:{1,-1.9715e-07,5.20684e-09,1.9715e-07,1,-1.18337e-09,-5.20684e-09,1.18337e-09,1}
    Axis #0 (phi):  {1,-0.0025,0.0056}
    Axis #1 (chi):  {-0.006,-0.0264,-0.9996}
    Axis #2 (omega):  {1,0,0}
    Angles: 0,-1.13e-05,0
    scan axis: #0 (phi)
```

**Comment by phyy-nx** [comment] 2019-11-22 17:56
Not remembering where, but this did come up recently, right?  Same response.  It's fine to change how stills are identified, as long as that change propagates through all the code and as long as dials.stills_process always picks the right stills indexer and stills integrator.  Using `if expt.scan is None` is the current convention (same with gonio) and is used all over in the code in dials.  There are also checks like this in iota and in cctbx's spotfinder.

Deleting scan/gonio is important for two reasons.  First, it guarantees that any downstream code that makes assumptions on scan/gonio that are invalid for stills is certain to fail if the scan/gonio are gone.  This happened all the time during the development of dials and was one of the ways I made sure stills were being properly treated through the whole processing pipeline.  Second, many stills are collected with invalid image headers, where an oscillation is in the header but the stills were recorded at an xfel or with a fixed gonio.  Deleting the scan/gonio in stills_process ensures the stills indexer and integrator are chosen.

For reference, see the function is_still in experiment.h:
https://github.com/cctbx/dxtbx/blob/master/model/experiment.h#L149-L154
Used (for example) here:
https://github.com/dials/dials/blob/master/algorithms/integration/integrator.py#L1593-L1612
It keys off of no scan/gonio, so deleting those ensures the file is treated as a still, and ensures if the scan is wrong in the header, the scan.oscillation=0 clause doesn't trigger.

THAT ALL SAID.  I see you are proposing only deleting the scan/gonio for ImageSequences? 
 Unfortunately the distinction between ImageSet and ImageSequence is totally lost on me.  This api change happened without me really understanding what was going on.  I'd be happy if someone could help me understand better?  Than maybe I could be brought on board with this proposal?

Thanks.

**Comment by dagewa** [comment] 2019-11-22 21:32
For the record, paper trail leads back to #970, #971

**Comment by dagewa** [comment] 2019-11-22 21:35
This is essentially a duplicate of #971 :roll_eyes:

**Comment by graeme-winter** [comment] 2019-11-22 21:51
@dagewa well spotted - I suspect #930 could probably be at least partially revived now, with the better insight

@phyy-nx the distinction you highlight here is key

An ImageSequence is precisely identical to an ImageSweep (which it has replaced) with the requirement that the rotation angle per frame is greater than zero removed.

It is necessary to keep the goniometer in the experiment to allow grids taken at multiple settings to be analysed, and the scan is necessary to index into the sequence - without these the resulting experiments no longer hold useful meaning for sequences. 

As you say, I do not propose we change the behaviour for ImageSets - if there was never a gonio (a key property of the Set) rather allow the sequence to be used beyond spot finding for getting data analysis done. 

I do not propose making any changes which will alter the behaviour of stills process one jot. My considerations are focussed on synchrotron analysis for e.g. grids.

**Comment by phyy-nx** [comment] 2019-11-22 22:43
Right, leaving aside stills process, dials.integrate also treats stills correctly by testing is_still.  I think the thing I'm missing here is understanding how the factory function, IntegratorFactory, would work, given your proposal.

Perhaps a set of use cases would help?  I'll write down what I believe currently happens, and you could propose changes?  In all these use cases, dials.import is called on either 1 hdf5 file or a directory full of cbfs.

Use case 1: a traditional sweep.  Result: a single experiment with a scan/gonio with oscillation > 0 and an ImageSequence.
Use case 2: real stills with good headers.  Result: many experiments, no scan/gonio, many ImageSets
Use case 3: stills with wrong headers (include oscillation but no oscillation was used), but convert_sequences_to_stills is specified.  Result, many experiments, many ImageSets, many scan/gonios with wrong, non-zero oscillation values.

dials.index and dials.integrate factory choices:
Use case 1: Sweep indexer/integrator
Use case 2: Stills indexer/integrator
Use case 3: Sweep indexer/integrator (this is wrong, need to use dials.stills_process to delete scan/gonios. There's no current way to do this with dials.import)

Now we add use case 4: a grid scan of stills. I don't really understand use case 4, either the current implementation that creates a grid scan instead of a normal scan, or the proposed implementation.  How are the headers structured?  What is the dials.import command to make a grid scan?  What is the result of dials.import?  Which indexer/integrators are chosen by the factories?

Thanks for bearing with me.

**Comment by graeme-winter** [comment] 2019-11-23 05:47
Use case 4: real stills with good headers from a synchrotron beamline where we do have a goniometer. Result: many experiments with scans and goniometers but one image sequence - this is WIP in a couple of branches.

I want to be able to record grid scans of samples at multiple orientations, so need the gonio, it should be a single sequence to allow efficient processing by analogy with sweep processing. I make no assumptions as to _which_ algorithms will be used. `scan.is_still()` will however return `True`

Command to make: dials.import
Headers structured: as usual
Result of dials.import:

```
Silver-Surfer demo :) $ dials.import ../Puck3_10_1_*cbf
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.1141-g99e83dc56
The following parameters have been modified:

input {
  experiments = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatCBFFullPilatusDLS6MSN126.FormatCBFFullPilatusDLS6MSN126'>
  num images: 230
  sequences:
    still:    1
    sweep:    0
  num stills: 0
--------------------------------------------------------------------------------
Writing experiments to imported.expt
```

i.e. one still sequence. Recognising use case 3 I have just added #1035 to provide the correct route in to the existing set based stills pipeline.

**Comment by phyy-nx** [comment] 2019-11-26 17:05
Thanks for the clarification.  I can't do any testing on my own with the new scan dataset or on cctbx/dxtbx#118 until after the US break.

**Comment by graeme-winter** [comment] 2019-12-16 09:28
Implementing changes in 

https://github.com/dials/dials/tree/dials-1029-30

and running all the dials tests as I go.

**Closed** 2020-02-05 11:50 UTC
Labels: validate
