### ISSUE TITLE
In reciprocal lattice viewer, if indexed, give option to show in crystal frame

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#487] opened 2017-12-29 08:13 UTC
i.e. divide through by U matrix so that multiple crystals (which are differently orientated) will be shown in same local coordinate system. 

This is complicated because:
 - indexing ambigiuty
 - different symmetries

But would still be useful to assess e.g. completeness of data from _n_ samples if indexed.

**Comment by graeme-winter** [comment] 2018-01-08 18:31
Reason for this occurred to me - if multi crystal, show _which_ crystals give you which reflections...

**Comment by graeme-winter** [comment] 2018-01-08 18:31
i.e. different to multiplicity viewer

**Comment by ndevenish** [comment] 2020-02-05 10:59
Duplicate of #279

**Closed by ndevenish** 2020-02-05 10:59 UTC
