### ISSUE TITLE
iDials test still broken

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#393] opened 2017-06-27 08:08 UTC

**Comment by graeme-winter** [comment] 2017-06-27 08:09
```
libtbx.python "/dls/science/users/gw56/svn/cctbx/modules/dials/test/command_line/tst_idials.py" [FAIL]
  Time: 81.76
  Return code: 1
  OKs: 1
  Standard error:
    Traceback (most recent call last):
      File "/dls/science/users/gw56/svn/cctbx/modules/dials/test/command_line/tst_idials.py", line 80, in <module>
        test.run()
      File "/dls/science/users/gw56/svn/cctbx/modules/dials/test/command_line/tst_idials.py", line 52, in run
        stdin_lines=stdin_lines).raise_if_errors()
      File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/libtbx/easy_run.py", line 39, in raise_if_errors
        raise Error(msg)
    RuntimeError: child process stderr output:
      command: 'idials'
      Sorry: no reflections for export
      Sorry: no reflections for export

```

**Comment by graeme-winter** [comment] 2017-06-27 08:09
Caused by export_mtz now saying Sorry if no reflections pass through for export; so was always empty but not caught error before; assume not writing any reflections not counted as useful test?

**Comment by jmp1985** [comment] 2017-06-27 08:24
Now should be fixed

**Closed by jmp1985** 2017-06-27 08:24 UTC

**Comment by Anthchirp** [comment] 2017-06-27 09:06
Thank you
