### ISSUE TITLE
dials.reciprocal_lattice_viewer borken

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#806] opened 2019-06-05 14:22 UTC
With multi-sweep data sets - in 1.14.x it looks like:
![Screen Shot 2019-06-05 at 15 20 53](https://user-images.githubusercontent.com/1241716/58963788-b060d380-87a5-11e9-8df8-50d2962ef7fb.png)

Which is correct but in master like
![Screen Shot 2019-06-05 at 15 21 01](https://user-images.githubusercontent.com/1241716/58963803-b6ef4b00-87a5-11e9-8232-1c3a20b3038d.png)

Which is wrong - any ideas? This is with the data in `/dls/tmp/gw56/53*`

**Comment by rjgildea** [comment] 2019-06-05 14:31
Something looks wrong with the geometry, even just looking at the first experiment (0), with 1.14:
![image](https://user-images.githubusercontent.com/2810624/58964492-e3f02d80-87a6-11e9-8594-2445f5151c19.png)
with dials/latest:
![image](https://user-images.githubusercontent.com/2810624/58964528-f5393a00-87a6-11e9-9a91-d5421182e8ab.png)

**Comment by benjaminhwilliams** [comment] 2019-06-05 14:35
Duplicate of #747?

**Comment by rjgildea** [comment] 2019-06-05 14:43
It looks like the RLV code still uses imagesets, when it would be better off using experiments.

**Comment by ndevenish** [comment] 2019-06-05 15:12
Sorry, didn't realise you had self-assigned!

**Closed** 2019-06-05 15:11 UTC

**Comment by graeme-winter** [comment] 2019-06-05 15:14
@ndevenish @rjgildea thanks chaps, fix is good (appreciate that there is work in progress here but it is now _working_)
