### ISSUE TITLE
Do not read STDIN by default

### ISSUE THREAD

**Issue by dagewa** [dials/dials#466] opened 2017-11-07 15:05 UTC
As discussed by email, prefer to explicitly request reading of PHIL parameters from STDIN, e.g. by use of a `phil=-` option, rather than always doing this implicitly. Text of email from Markus:

> relevant code:
> https://github.com/dials/dials/blob/f5e585405fbe67534c90cb134161d937d8e5e603/util/options.py#L711-L717
> 
> The reason for istty() checking is that at the moment dials commands allow phil parameters coming in via STDIN. So you can do
>  $ dials.stuff < parameters.phil
> 
> or if you prefer creating additional processes and abusing the cat command you can rewrite this as:
>  $ cat parameters.phil | dials.stuff
> 
> Problem is of course that you don't want dials commands reading STDIN when run interactively, otherwise you'd have to press CTRL+D before dials.stuff would do anything. So we check if the input is a TTY, and if it is, we don't try to read from it.
> 
> It is naturally very difficult (read: impossible) to distinguish between a legitimate
>  $ something-producing-output-which-may-not-be-instantaneous | dials.stuff
> and
>  $ dials.stuff < pipe-from-a-program-running-dials-which-does-not-close-stdin > pipe-back-to-the-program 2> pipe-stderr
> 
> So if we are to add a command line flag then I would rather not have a --disable-tty-check and instead have a --read-phil-parameters-from-stdin (with a less clunky name but you get the idea) and change the default behaviour to not read STDIN.
> Besides, this would open up individual dials commands to use STDIN for specific stuff other than phil parameters.
> 
> Maybe something like "phil=-" would be acceptable, with '-' being the standard name for STDIN/STDOUT in the unix world, cf.
>  $ wget http://example.com -O - | vim -R -
> 
> -Markus
>

**Comment by jmp1985** [comment] 2017-11-17 13:10
@ndevenish You were going to look at improving the command line input in general I think? Is this something that you are currently implementing as part of the wider modifications? If so, I'll assign this to you!

**Comment by dagewa** [comment] 2018-02-21 14:25
Hi, any progress on this? Kyle from CCP4 needs it for launching `dials.image_viewer` and `dials.reciprocal_lattice_viewer` from ccp4i2.

**Comment by luisodls** [comment] 2018-05-24 15:46
We (me and Kyle) have issues with this ... ccp4i2 developers struggle to connect to DIALS

**Comment by ndevenish** [comment] 2018-05-24 15:59
We can prioritise this if it's needed I guess...

But I forget what the exact problem was at the moment? As far as I can tell from a quick glance, it only reads if not a tty, and if it is a tty then a read on an empty STDIN should just get EOF? And phil parameters can be passed via arguments otherwise?

Probably there is some complication I'm not remembering...

**Comment by ndevenish** [comment] 2018-05-31 11:47
After speaking to @luisodls the `QProcess` problem seems to be because he was opening a subprocess with a hanging, unclosed STDIN, which could cause problems with anything. I'm not a QT expert, but [`QProcess.closeWriteChannel`](http://doc.qt.io/archives/qt-4.8/qprocess.html#closeWriteChannel) seems to fix that (not sure if a way to open without a dangling STDIN akin to python.subprocesses `stdin=None`, but I'd imagine so).

@dagewa, would this be the cause of the CCP4i2 problems also?

Not to suggest that this shouldn't go away to a more visible interface.

**Closed** 2018-07-09 17:54 UTC
