### ISSUE TITLE
dials.merge does not write a space group name P2111

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#2684] opened 2024-06-27 08:26 UTC
I have a pseudo-orthorhombic dataset that can be *roughly* solved in P212121 but is not quite right. Trying to find out which axis has the crystallographic symmetry, I tried merging in P2111, P1211 and P1121 by running e.g. `dials.cosym space_group=P2111` followed by `dials.scale symmetrized.{expt,refl}`.

```
$ dials.show scaled.expt | grep Space
    Space group: P 21 1 1
    Space group: P 21 1 1
... # several crystals were merged. All P 21 1 1 as expected

$ dials.export scaled.{expt,refl}
 Space Group: P 21 1 1
 Space Group Number: 0

$ echo GO | mtzdump hklin scaled.mtz | grep Space
 * Space group = 'P 21 1 1' (number     0)
```

So far, everything is fine.
However, `dials.merge` does something weird.

```
$ dials.merge scaled.{expt,refl}

 Writing reflections to merged.mtz
 Title: From dials.merge
 Space group symbol from file: No.4 # This is not a SYMBOL!
 Space group number from file: 4
 Space group from matrices: P 21 1 1 (No. 4)
 Point group symbol from file: 2

$ echo GO| mtzdump hklin merged.mtz|grep Space
 * Space group = 'No.4' (number     4) # !?
```

Servalcat fails because "No.4" is not a space group name.
Why cannot `dials.merge` write `P 21 1 1`, while `dials.export` can?

I cannot upload this dataset because it is unpublished, but I guess you can reproduce this issue on other orthorhombic or tetragonal datasets (e.g. lysozyme). If you cannot, I will share the dataset privately.

**Comment by dagewa** [comment] 2024-06-27 08:34
My first guess is that this might be because `dials.export` of an unmerged MTZ uses gemmi, whereas creation of merged MTZs still uses `iotbx.mtz`. This reminds me that I wanted to follow up https://github.com/dials/dials/pull/2380 by changing _all_ MTZ handling in DIALS to use gemmi. I just haven't found time to do that yet.

**Comment by dagewa** [comment] 2024-06-27 09:22
The issue can be reproduced by these commands:
```
dials.import $(dials.data get -q thaumatin_i04)/*.cbf
dials.find_spots imported.expt
dials.index imported.expt strong.refl
dials.index imported.expt strong.refl space_group=P2111
dials.refine indexed.{expt,refl}
dials.integrate refined.{expt,refl}
dials.scale integrated.{expt,refl}
dials.export scaled.{expt,refl}
dials.merge scaled.{expt,refl}
```

**Comment by biochem-fan** [comment] 2024-06-27 11:47
@keitaroyam pointed out that the following line is the cause.

https://github.com/cctbx/cctbx_project/blob/c779886e73a4f5d036a9c3abfa19e5fe74e2b521/iotbx/mtz/__init__.py#L266-L272

Why wan't `str(space_group_info)` used instead?

**Closed** 2024-08-06 08:39 UTC
