### ISSUE TITLE
image_viewer badly handling combined data

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#878] opened 2019-08-07 14:51 UTC
Combined a whole load of (small-sweep) experiments to do joint refinement - all of the shoeboxes appear to be displayed on the first sweep e.g.

![image](https://user-images.githubusercontent.com/529963/62632734-df70fe00-b92a-11e9-9fa0-2d973176d2d8.png)

possibly quite related to #632, though seems a slightly different problem.

**Comment by ndevenish** [comment] 2019-08-07 14:54
Present in 1.14 so not introduced/reintroduced in 2.0

**Comment by graeme-winter** [comment] 2019-08-08 07:46
This does not surprise me - the selections in the image viewer are very single-sweep - probably needs to augment with something which checks that the image corresponds to the experiment and use the experiment id as well as the frame number in the filtering.

But will get messy

**Comment by graeme-winter** [comment] 2019-08-08 12:41
See also https://github.com/dials/dials/issues/505

**Comment by benjaminhwilliams** [comment] 2020-02-05 10:59
It turns out this is a duplicate of #1093.

**Closed** 2020-02-05 11:00 UTC
Labels: duplicate
