### ISSUE TITLE
dials.export seems to require the image data for exporting mtz data. 

### ISSUE THREAD

**Issue by jmp1985** [dials/dials#639] opened 2018-10-24 11:00 UTC
It would be nice for dials.export to not require this. It seems that now an environment variable needs to be set (DIALS_EXPORT_DO_NOT_CHECK_FORMAT) but couldn't this be achieved in a more sensible way?

**Comment by jbeilstenedmands** [comment] 2018-10-24 11:20
See #484 for previous work on this

**Comment by rjgildea** [comment] 2018-10-24 11:29
The problem is that you have to enforce this check at the point of the option parser. If you this check could somehow occur at the point of requesting the raw image data then this problem could be eliminated.

**Comment by ndevenish** [comment] 2019-09-10 15:29
Duplicate of #484

**Closed by ndevenish** 2019-09-10 15:29 UTC
