### ISSUE TITLE
squashed paths

### ISSUE THREAD

**Issue by dermen** [dials/dials#2693] opened 2024-07-06 02:36 UTC
In a situation where my input glob of 7000 CBF files to stills_process "cbfs/*.cbf"  gets comrpessed down to 73 files or so.. Is this the expected behavior ?

I made a simple reproducer below, copying the relevant files from stills_process

```
```

**Comment by ndevenish** [comment] 2024-09-17 13:20
This seems to have no data!?

**Comment by toastisme** [comment] 2024-09-17 13:44
Closing as duplicate of #2694

**Closed by toastisme** 2024-09-17 13:44 UTC
