### ISSUE TITLE
Python 3.7 and 3.8 support

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#1236] opened 2020-04-15 18:50 UTC
I was testing cctbx/cctbx_project#409 with the dials builder to see how far it got and it stopped on base, since dials/.conda-envs/dials_py38_linux-64.txt is not available.  Perhaps this issue could serve as a starting point for getting python 3.7 and 3.8 working in dials?  First step would be getting the recipes ready.

**Comment by Anthchirp** [comment] 2020-04-15 19:15
I have looked at this in the past and found some known package restrictions that hold back 3.8 support:
https://github.com/dials/dials/blob/1d438bf3ae70e1180876cd248a080bc29ddb70f9/.conda-envs/linux.txt#L12-L38

ie. we'd need to update and validate matplotlib, biopython, scikit-learn, scipy, and sphinx.

I've updated numpy (80b50b0f1ab6d3703a18199721abd2d3c35140bd), this was required to fix #1193, and fixed the conda-forge 3.8 package for orderedset already, but haven't had the time to look at more of them yet. 3.8 support is not currently urgent for us, and there was no point looking at this in more detail until cctbx/cctbx_project#409 was ready.

I'll probably wait until it goes in before I revisit this.

**Comment by Anthchirp** [comment] 2020-06-12 00:05
With the essential dependency updates applied the current status is:
* Linux: 3.7 ✔️ 
* Linux: 3.8 ✔️ 
* MacOS: 3.7 ❌ 4 tests fail
  * `test_index_after_search`: `concurrent.futures.process.BrokenProcessPool`
  * `test_setting_c2_vs_i2[False-C 1 2 1-expected_unit_cell1]`: `concurrent.futures.process.BrokenProcessPool`
  * `test_search_small_molecule`: `concurrent.futures.process.BrokenProcessPool`
  * `test_show_extensions`: `libtbx.easy_run` returns `RuntimeError: non-zero return code: -6`
* MacOS: 3.8 ❌ 2 tests fail
  * `test_find_spots_server_client`: `TypeError: cannot pickle '_thread.lock' object`
  * `test_preservation_of_identifiers`: `UserWarning: resource_tracker: There appear to be 4 leaked semaphore objects to clean up at shutdown`
* ⚠️ a bunch of new deprecation warnings we can easily ignore until 3.9 is released in October (so beyond the scope of #1175)

https://dev.azure.com/azure-dials/dials/_build/results?buildId=155&view=results

**Comment by Anthchirp** [comment] 2020-06-16 07:51
As it stands I think we can say we are not 3.7+ compatible, and some remedial effort is required before we can pretend to be 3.7+ compatible.

The 3.7 errors are interesting, as neither I nor @graeme-winter can reproduce them on a different machine. However they are 100% reproducible on Azure, so they are real problems.

The 3.8 errors are probably worse and most likely correlate with the move from fork to spawn. Running
```
dials.refine /dls/science/groups/scisoft/DIALS/repositories/git-reference/dials_regression/refinement_test_data/multi_stills/combined_experiments.json /dls/science/groups/scisoft/DIALS/repositories/git-reference/dials_regression/refinement_test_data/multi_stills/combined_reflections.pickle outlier.algorithm=null engine=LBFGScurvs output.reflections=None output.experiments=refined_nproc4.expt nproc=4
```
crashes one process with
```
1167 reflections remain in the manager
There are 57 parameters to refine against 1167 reflections in 3 dimensions
Performing refinement of 10 Experiments...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/wra62962/bootstrap/conda_base/python.app/Contents/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/wra62962/bootstrap/conda_base/python.app/Contents/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
RuntimeError: This class cannot be instantiated from Python
```
which does not sound nice. The main process then gets stuck 6 layers deep in `multiprocessing` which is hidden behind 7 layers of `libtbx.easy_*`, so I'm unlikely to find the time to look at this any time soon.

**Comment by graeme-winter** [comment] 2020-06-16 07:58
I can't help but think that a lot of our problem here is going through the `libtbx.easy_mp` route which hides implementation details and swallows exceptions. If we were just using native Python parallelism tools (concurrent futures, to pick a random example) our life would be a bucket easier, with the happy side-effect of things actually working on Windows, which is a non-trivial fraction of out end user base.

**Comment by Anthchirp** [comment] 2020-06-25 11:11
So the 3.7/3.8 issues on MacOS need a bit more investigative effort.
What I think we can do though is enable Azure builds for Linux 3.7/3.8 and that way at least ensure those keep working.

**Comment by Anthchirp** [comment] 2020-07-07 21:51
The 3.7 build seems to be stable now.

Breakthrough on 3.8, too: The leaked semaphores originate from https://github.com/dials/dials/blob/2ad7531489cf4b869fcc2e23ee6780dd6ec06692/util/_progress.py#L24
and are [fixed by updating tqdm](https://github.com/dials/dials/commit/5a98821eba303f7ea9557bb8127f34b1c1fe3112) ([Azure results](https://dev.azure.com/azure-dials/dials/_build/results?buildId=460&view=ms.vss-test-web.build-test-results-tab))

The tqdm update breaks the associated tqdm tests, so those will need some attention. Looks like that would be a good opportunity to address #1255, too.

**Comment by Anthchirp** [comment] 2020-07-07 23:05
The remaining 3.8 error is that `dials.find_spots_server` is broken with spawn multiprocessing. If the server is still used it probably would benefit from being rewritten using something like flask+uwsgi. Since it's not really something that the average DIALS user will ever come in contact with I suggest disabling the associated test for 3.8+spawn.

**Comment by Anthchirp** [comment] 2020-07-09 14:54
There's a potential issue in procrunner for 3.8 (https://github.com/DiamondLightSource/python-procrunner/issues/47), but ideally need a catalina machine to confirm

**Comment by Anthchirp** [comment] 2020-07-09 18:04
@graeme-winter gave me access to a catalina computer and I did not found anything of relevance, apart from the tqdm update requirement - see above pull request.

**Closed** 2020-07-16 15:24 UTC
