### ISSUE TITLE
exclude_datasets="10 50 79"

### ISSUE THREAD

**Issue by TH-Chang** [dials/dials#1253] opened 2020-05-10 15:29 UTC
Hi 
I was wondering where 10 is the number of sweep (for example sweep10 in this case?) that used in xia2? Thank you.

**Comment by benjaminhwilliams** [comment] 2020-05-11 08:28
Hi @TH-Chang, I'm not entirely clear on the details of your issue.  First of all, is this a problem you are having with xia2?  xia2 is actually a separate project to DIALS, though it makes use of DIALS and shares some of the same developers.  You can find the repository for xia2 at https://github.com/xia2/xia2 and there is an email address for support too, xia2.support@gmail.com, in case you prefer to send us an email.

If this is a problem you are having with DIALS, rather than xia2, could you provide a few more details of what you're trying to achieve and what doesn't seem to work?

**Comment by TH-Chang** [comment] 2020-05-11 15:20
Hi Ben Williams,
Thank you for the clarification. I should ask this question in xia2 for whether the command "exclude_datasets="10 50 79" can be used in xia2 interface.
Thank you.

**Comment by benjaminhwilliams** [comment] 2020-05-11 17:22
Closing as a duplicate of xia2/xia2#448.

**Closed by benjaminhwilliams** 2020-05-11 17:22 UTC
